services:
  anvil:
    build:
      context: ./hardhat-node
      dockerfile: Dockerfile
    ports: ["8545:8545"]

  mock-paymaster:
    image: ghcr.io/pimlicolabs/mock-verifying-paymaster:main
    ports: ["3000:3000"]
    environment:
      - ALTO_RPC=http://alto:4337
      - ANVIL_RPC=http://anvil:8545

  alto:
    image: ghcr.io/pimlicolabs/mock-alto-bundler:main
    ports: ["4337:4337"]
    command: "--log-level info"
    environment:
      - ANVIL_RPC=http://anvil:8545
